export const SALESPEOPLE = [
  'Alexandre Silva',
  'Ana Carolina Souza',
  'Bruno Ferreira',
  'Carlos Eduardo Lima',
  'Daniela Martins',
  'Eduardo Oliveira',
  'Fernanda Costa',
  'Gabriel Santos',
  'Helena Rodrigues',
  'Igor Pereira',
  'Juliana Alves',
  'Lucas Mendes',
  'Mariana Carvalho',
  'Nelson Barbosa',
  'Patricia Nascimento',
  'Rafael Gomes',
  'Renata Freitas',
  'Rodrigo Araujo',
  'Tatiana Moreira',
  'Thiago Ribeiro',
]
